name: GitHub Snake

on:
  schedule:
    - cron: '0 * * * *' # roda a cada hora
  workflow_dispatch:

jobs:
  snake:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Snake Game
        uses: platane/snk@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
